### ISSUE TITLE
GNU sed command does not work on OSX

### ISSUE THREAD

**Issue by vnckppl** [NYU-DiffusionMRI/Diffusion-Kurtosis-Imaging#2]
Hi Jelle,

In designer_2.sh you call sed with '-r' (on line 133). This option is only available in GNU sed, not in BSD sed which comes with OSX. Is there a way you could fix this? 

Thanks!

- Vincent

**Comment by badesar1** [comment]
Unfortunately, the designer pipeline is only running on linux for now, but I can upload a version written in python instead which you may find helpful.

**Comment by vnckppl** [comment]
Alright, no worries and thanks for your quick response. I will try and see if installing GNU sed via homebrew fixes the issue.
