### ISSUE TITLE
mrtrix/bin PATH error on OS X

### ISSUE THREAD

**Issue by LRAlvarado** [NYU-DiffusionMRI/Diffusion-Kurtosis-Imaging#4]
Hi,
I get this error when trying to run DESIGNER.py on OS X:

cannot find path to mrtrix3, please make sure <path/to/mrtrix3/bin> is in your PATH

However, I have set my .bash_profile as follows:
__________________________________________________________

#added by Anaconda2 4.4.0 installer
export PATH="/Users/lralvarado/anaconda/bin:$PATH"

#MRtrix3
MRTRIXDIR=/usr/local/Cellar/mrtrix3/3.0_RC2-82-gbb77205e
PATH=${MRTRIXDIR}/bin:${PATH}

#SPM12
export SPM_PATH=/usr/local/MATLAB/R2017a/toolbox/spm12/

#FSL Setup
FSLDIR=/usr/local/fsl
. ${FSLDIR}/etc/fslconf/fsl.sh
PATH=${FSLDIR}/bin:${PATH}
export FSLDIR PATH

#FREESURFER Setup
#export SUBJECTS_DIR=/Users/lralvarado/Documents/test_run/subjects/
export FREESURFER_HOME=/Applications/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh 

__________________________________________________________

I am a fairly new to working with the terminal in OS X and python. Perhaps I am missing something.

**Comment by badesar1** [comment]
Your .bash_profile looks fine. I see you installed mrtrix3 via homebrew. I did not originally support this, but the problem should be fixed now. Try updating DESIGNER.py and let me know if you have any further issues getting the program running. 

Best,
Ben

**Comment by LRAlvarado** [comment]
Thank you for the speedy response!
The update worked. I was able to run DESIGNER.py after updating.
